// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLEMjf7mRP6EKhWxep4GU9g7aLowvHH0',
    appId: '1:90529643559:web:77af1386edbe64bb8ca202',
    messagingSenderId: '90529643559',
    projectId: 'chat-app-flutter-c528f',
    authDomain: 'chat-app-flutter-c528f.firebaseapp.com',
    storageBucket: 'chat-app-flutter-c528f.firebasestorage.app',
    measurementId: 'G-0WX4M1ZLM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGl3mGBW9pphSEstci529pcPPSvQZco8A',
    appId: '1:90529643559:android:f4314a3675dd8c818ca202',
    messagingSenderId: '90529643559',
    projectId: 'chat-app-flutter-c528f',
    storageBucket: 'chat-app-flutter-c528f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxt8vq3YFj4p5_YeUMPM3WxyFUUWPVBs',
    appId: '1:90529643559:ios:9c5770c05c057b598ca202',
    messagingSenderId: '90529643559',
    projectId: 'chat-app-flutter-c528f',
    storageBucket: 'chat-app-flutter-c528f.firebasestorage.app',
    iosBundleId: 'com.example.chattingAppFlutter',
  );
}
